### GetMe
GET http://localhost:8899/api/auth/me HTTP/1.1

### Login
POST http://localhost:8899/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "identity" : "pp222@gmail.com",
    "password" : "123456"
}

### Register
POST http://localhost:8899/api/auth/register HTTP/1.1
Content-Type: application/json

{
  # "identity":"0616637894",
  "mobile": "9876543210",
  "email" : "pp222@gmail.com",
  "firstName": "p",
  "lastName" : "cc20",
  "password" : "123456",
  "confirmPassword" : "123456"

}