### GetMe
GET http://localhost:8899/api/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzUwOTA5MDU2LCJleHAiOjE3NTIyMDUwNTZ9.6W3951Migb0Ohi-URloX2TJO7Mtslu36jghHQK5DcD8

### Login
POST http://localhost:8899/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "identity" : "bobby@ggg.mail",
    "password" : "123456"
}

### Register
POST http://localhost:8899/api/auth/register HTTP/1.1
Content-Type: application/json

{
  # "identity":"0616637894",
  "mobile": "9876543210",
  "email" : "pp222@gmail.com",
  "firstName": "p",
  "lastName" : "cc20",
  "password" : "123456",
  "confirmPassword" : "123456"

}